#!/bin/sh

case "$1" in

    configure)
        # enable on boot
        update-rc.d japt defaults
        invoke-rc.d japt restart
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

exit 0

# vim:set ts=4 sw=4 expandtab:
