#!/bin/sh

case "$1" in
    remove|upgrade)
        # stop the server
        invoke-rc.d japt stop
        ;;
    deconfigure)
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
            exit 1
        ;;
esac

exit 0

# vim:set ts=4 sw=4 expandtab:
